/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trabajofinaljavaulp.Vistas;

import java.util.ArrayList;
import java.util.regex.*;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentListener;
import javax.swing.event.DocumentEvent;
import trabajofinaljavaulp.datos.InmuebleDatos;
import trabajofinaljavaulp.datos.PropietarioDatos;
import trabajofinaljavaulp.entidades.Inmueble;
import trabajofinaljavaulp.entidades.Propietario;

/**
 *
 * @author HP
 */
public class InmuebleView extends javax.swing.JInternalFrame {

    Inmueble inmueble = null;
    /**
     * Creates new form InmuebleView
     */
    public InmuebleView() {
        initComponents();
        actualizarComboBox();
        rellenarComboBox(); 
    }
    
    public InmuebleView(int id) {
        initComponents();
        actualizarComboBox();
        rellenarComboBox();
        
        inmueble = InmuebleDatos.buscar(id, true);
        
        jtBuscarProp.setText(inmueble.getPropietario().toString()); //Funcionara?
        
        jtDireccion.setText(inmueble.getDireccion());
        jtPrecio.setText(Double.toString(inmueble.getPrecio()));
        jtSuperficie.setText(Double.toString(inmueble.getSuperficie()));
        jcbTipo.setSelectedItem(inmueble.getTipo());
        jbNuevo.setText("Guardar");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbNuevo = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jtBuscarProp = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtPrecio = new javax.swing.JTextField();
        jcbPropietario = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtSuperficie = new javax.swing.JTextField();
        jtDireccion = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jbNuevoPropietario = new javax.swing.JButton();
        jcbTipo = new javax.swing.JComboBox<>();

        setClosable(true);
        setResizable(true);
        setTitle("Ingreso de Datos-Inmueble");
        setMaximumSize(new java.awt.Dimension(2147483647, 350));
        setMinimumSize(new java.awt.Dimension(600, 350));
        setPreferredSize(new java.awt.Dimension(620, 350));

        jbNuevo.setText("Nuevo");
        jbNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNuevoActionPerformed(evt);
            }
        });

        jLabel6.setText("Precio:");

        jLabel3.setText("Tipo:");

        jLabel2.setText("Direccion: ");

        jLabel7.setText("Buscar propietario:");

        jLabel4.setText("Superficie:");

        jLabel1.setText("Seleccionar propietario:");

        jLabel5.setText("m2");

        jbNuevoPropietario.setText("+");
        jbNuevoPropietario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbNuevoPropietario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNuevoPropietarioActionPerformed(evt);
            }
        });

        jcbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "LOCAL", "DEPOSITO", "DEPARTAMENTO", "OFICINA" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(268, 268, 268))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addGap(63, 63, 63)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtBuscarProp)
                            .addComponent(jtDireccion)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jcbPropietario, 0, 368, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbNuevoPropietario))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                                    .addComponent(jtSuperficie))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jcbTipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jtBuscarProp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jcbPropietario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbNuevoPropietario))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jcbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtSuperficie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbNuevo)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbNuevo)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNuevoActionPerformed
        try {
            Propietario propietario = (Propietario) jcbPropietario.getSelectedItem();
            String direccion = jtDireccion.getText();
            double precio = Double.parseDouble(jtPrecio.getText());
            double superficie = Double.parseDouble(jtSuperficie.getText());
            String tipo = jcbTipo.getSelectedItem().toString();
            
            //Si algun campo esta vacio
            if (direccion.trim().isEmpty() || tipo.isEmpty()) {
                throw new IllegalStateException();
            }
            
            if (jbNuevo.getText().equals("Nuevo")) {
                InmuebleDatos.agregar(new Inmueble(direccion, propietario, tipo, superficie, precio, true));
            } else {
                inmueble.setPropietario(propietario);
                inmueble.setDireccion(direccion);
                inmueble.setPrecio(precio);
                inmueble.setSuperficie(superficie);
                inmueble.setTipo(tipo);
                InmuebleDatos.modificar(inmueble);
            }
            
            this.dispose();
        } catch (IllegalStateException | NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Formulario incompleto", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbNuevoActionPerformed

    private void jbNuevoPropietarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNuevoPropietarioActionPerformed
        JDesktopPane escritorio = this.getDesktopPane();
        escritorio.repaint();
        PropietarioView pV=new PropietarioView();
        pV.setVisible(true);
        escritorio.add(pV);
        escritorio.moveToFront(pV);
    }//GEN-LAST:event_jbNuevoPropietarioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbNuevo;
    private javax.swing.JButton jbNuevoPropietario;
    private javax.swing.JComboBox<Propietario> jcbPropietario;
    private javax.swing.JComboBox<String> jcbTipo;
    private javax.swing.JTextField jtBuscarProp;
    private javax.swing.JTextField jtDireccion;
    private javax.swing.JTextField jtPrecio;
    private javax.swing.JTextField jtSuperficie;
    // End of variables declaration//GEN-END:variables

    private void actualizarComboBox(){
        // Asocia un DocumentListener al JTextField jtBuscarProp
        jtBuscarProp.getDocument().addDocumentListener(new DocumentListener() {
            //new DocumentListener() es una clase anónima que implementa la interfaz DocumentListener
            @Override
            public void insertUpdate(DocumentEvent e) { //Se llama cuando se inserta texto el TextField
                rellenarComboBox();
            }

            @Override
            public void removeUpdate(DocumentEvent e) { //se llama cuando se elimina texto en el TextField
                rellenarComboBox();
            }

            @Override
            public void changedUpdate(DocumentEvent e) { //se llama cuando ocurre un cambio en el estilo de texto
                rellenarComboBox(); //en los tres métodos actualiza los resultados del método rellenarComboBox
                //                      garantiza que el comboBox refleje el estado actual del TextField
            }
        });        
    }
    
    //Hay algo raro porque al buscar no coincide la búsqueda con el resultado
    private void rellenarComboBox() {
        ArrayList<Propietario> listaPropietarios = PropietarioDatos.listar(true);
        ArrayList<Propietario> result = new ArrayList<>(); //A ESTA LISTA SOLO SE AGREGAN AQUELLAS COINCIDENCIAS
        Pattern busqueda = Pattern.compile(jtBuscarProp.getText(), Pattern.CASE_INSENSITIVE);
        jcbPropietario.removeAllItems();
        for (Propietario prop : listaPropietarios) {
            if (busqueda.matcher(prop.toString()).find()) {
                result.add(prop); //AGREGADO DE COINCIDENCIAS CON LO DEL TEXTFIELD
            }
        }
        DefaultComboBoxModel<Propietario> model = new DefaultComboBoxModel<>(result.toArray(new Propietario[0]));
        jcbPropietario.setModel(model);
    }
}
